### ISSUE TITLE
cmake build tool

### ISSUE THREAD

**Issue by proverbs** [prowiki/cpp-bootstrap#1]

**Comment by proverbs** [comment]
https://cliutils.gitlab.io/modern-cmake/chapters/intro/installing.html
https://cmake.org/cmake/help/latest/guide/tutorial/index.html#guide:CMake%20Tutorial
https://aiden-dong.github.io/2019/07/20/CMake%E6%95%99%E7%A8%8B%E4%B9%8BCMake%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E5%BA%94%E7%94%A8/
https://www.hahack.com/codes/cmake/

**Comment by proverbs** [comment]
cmake test? catch2?

**Comment by hooshooo** [comment]
done
